### PR TITLE
Add recipes for ruby 2.7.6 and 3.0.4

### PR DESCRIPTION
**Pull request by benjamineskola**

### CODE REVIEW

**Review by kevindew — APPROVED** [review]
Looks good to me, probably worth getting a review from someone in Platform Reliability too since this is in their ownership.

**Comment by kevindew** [comment]
Are you able to test that the recipe for 3.1.2 works and is installable? I think the 3.1.0 one isn't and I assume it could be dependency related.

**Comment by benjamineskola** [comment]
I haven't tested 3.1.2, I just thought it might be best to have it packaged rather than the older version nevertheless.

**Comment by benjamineskola** [comment]
As far as I can tell, 3.1.0 actually works: running from the packager repository using the dockerfile there, I can install the 3.1.0 deb file from Jenkins, and then switch to 3.1.0 using rbenv and run a simple script:

```
$ docker run -v ~/Downloads:/home -w /home trusty sh -c 'sudo dpkg -i ./rbenv-ruby-3.1.0_1_amd64.deb; export RBENV_ROOT=/usr/lib/rbenv RBENV_VERSION=3.1.0; eval "$(rbenv init -)"; ruby ./hello.rb'
Selecting previously unselected package rbenv-ruby-3.1.0.
(Reading database ... 19423 files and directories currently installed.)
Preparing to unpack ./rbenv-ruby-3.1.0_1_amd64.deb ...
Unpacking rbenv-ruby-3.1.0 (1) ...
Setting up rbenv-ruby-3.1.0 (1) ...
3.1.0
```

(`hello.rb` is just `puts RUBY_VERSION`.)

**Comment by kevindew** [comment]
Thanks @benjamineskola - it's probably worth checking in with @ChrisBAshton who had to do the revert of 3.1.0 https://github.com/alphagov/govuk-puppet/pull/11518

**Comment by benjamineskola** [comment]
Ah, I see, it's missing openssl from the standard library. I'm not sure why that would have broken for 3.1 but I can try to figure it out.

**Comment by benjamineskola** [comment]
Looks like the issue is that 3.1.x needs openssl >= 1.0.2 which we don't have packaged. I'll remove 3.1 from this PR to unblock the rest.

**Comment by kevindew** [comment]
> Looks like the issue is that 3.1.x needs openssl >= 1.0.2 which we don't have packaged. I'll remove 3.1 from this PR to unblock the rest.

Oh no so our ancient use of openssl 1.0.1 means we can't update Ruby versions any further.

**Comment by benjamineskola** [comment]
> Oh no so our ancient use of openssl 1.0.1 means we can't update Ruby versions any further.

Seems like it! I presume the steps are to package openssl 1.0.2 _alongside_ existing ones (because I expect that other packages will continue to depend on older versions) and then rebuild 3.1.x against that (probably explicitly passing a path to openssl, because it won't be the default).

**Review by MuriloDalRi — APPROVED** [review]

**Pull request merged**
