### PR TITLE
Add govuk-python3 package

### PR DESCRIPTION
**Pull request by kentsanggds**
## What

This will allow installation of a specific version of python 3 to be installed without affecting the govuk-python package already installed.

### CODE REVIEW

**Review by brucebolt — COMMENTED** [review]
It looks like we've already got a recipe for Python 3.6.12: https://github.com/alphagov/packager/blob/master/fpm/recipes/govuk-python-3.6.12/recipe.rb.  Is it possible to use this one?

**Comment by kentsanggds** [comment]
Problem is that it's not possible to use `python 2.7.14` and `python 3.6.12` on the same machine at the same time, this is fine for most cases but the CI agents need both. I need a later version of python as the default trusty one 2.7.6 doesn't support SNI which `pip` is now enforcing.

**Comment by brucebolt** [comment]
I'm trying to think of a way this can be done without needing to rebuild a package we already have, albeit just with a different name.

Would it instead by possible to duplicate the [`govuk_python` module in Puppet](https://github.com/alphagov/govuk-puppet/blob/57cc29472ed5429bda246dcde0b4c830c9dbc10c/modules/govuk_jenkins/manifests/packages/govuk_python.pp) with another that specifies 3.6.12 as the version (e.g. `govuk_python3`) then include the `govuk_python3` module [alongside `govuk_python`](https://github.com/alphagov/govuk-puppet/blob/57cc29472ed5429bda246dcde0b4c830c9dbc10c/modules/govuk_ci/manifests/agent.pp#L48) in the CI agent config?

**Comment by kentsanggds** [comment]
I don't think it's possible for 2 versions of the same package name to exist on the same machine, thats the main issue. 
When I went on one of the CI agents and tried to install python 2.7.14 it replaced 3.6.12.

**Comment by kentsanggds** [comment]
Alternatively I could install python 2 on a couple of CI machines and leave the rest as python 3 but then apps would have to know that certain agents have python 3 and not 2 installed which could cause some confusion.

**Review by brucebolt — APPROVED** [review]
Ah, ok, I see.  This seems like a reasonable solution then, until we can get all the Python 2.7 stuff upgraded to Python 3.

**Pull request merged**
